services:
  - type: web
    name: online-exam-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: MAVEN_VERSION
        value: 3.9.5
